apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   argocd.argoproj.io/hook: PreSync

resources:
  - create-bucket-job.yaml
  # - create-bucket-rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: create-bucket
    files:
      - create-bucket.py
