apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account-demo-setup.yaml
  - role-binding-demo-setup.yaml
  - create-ds-connection-secret.yaml
  - create-bucket-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: create-bucket-script
    namespace: ai-example-single-model-serving
    files:
      - create-bucket.py
