apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   argocd.argoproj.io/hook: PreSync

resources:
  - upload-model-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: upload-model-to-s3
    files:
      - upload-model-to-s3.py
