apiVersion: batch/v1
kind: Job
metadata:
  name: upload-model-to-s3
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: upload-model-to-s3
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2023.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: aws-connection-example
          env:
            - name: MODEL_NAME
              value: granite-3b-code-base
            - name: PREFIX_PATH
              value: "models"
            - name: MODEL_PATH
              value: "$(PREFIX_PATH)/$(MODEL_PATH)"
          command:
            - /bin/bash
          args:
            - -ec
            - |-
              env | grep AWS_
              python3 /scripts/upload-model-to-s3.py
          volumeMounts:
            - name: src
              mountPath: /opt/app-root/src
            - name: scripts
              mountPath: /scripts
      initContainers:
        - name: git-cloner
          image: alpine/git
          env:
            - name: MODEL_NAME
              value: granite-3b-code-base
            - name: REPO_URL
              value: https://huggingface.co/ibm-granite/granite-3b-code-base.git
          args:
            - clone
            - --single-branch
            - $(REPO_URL)
            - /opt/app-root/src/models/$(MODEL_NAME)
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: src
      volumes:
        - name: src
          emptyDir: {}
        - name: scripts
          configMap:
            name: upload-model-to-s3
      restartPolicy: Never
