apiVersion: batch/v1
kind: Job
metadata:
  name: create-ds-connections
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: create-ds-connections
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BUCKETNAME
              value: "multi-model-bucket"
          args:
            - -ec
            - |-
              echo -n 'Waiting for minio route'
              while ! oc get route minio-api 2>/dev/null | grep -qF minio; do
                echo -n .
                sleep 5
              done; echo

              echo -n 'Waiting for minio root user secret'
              while ! oc get secret minio 2>/dev/null | grep -qF minio; do
                echo -n .
                sleep 5
              done; echo

              MINIO_ROOT_USER=$(oc get secret minio -o template --template '{{.data.minio_root_user}}')
              MINIO_ROOT_PASSWORD=$(oc get secret minio -o template --template '{{.data.minio_root_password}}')
              MINIO_HOST=https://$(oc get route minio-api -o template --template '{{.spec.host}}')

              cat << EOF | oc apply -f-
              apiVersion: v1
              kind: Secret
              metadata:
                annotations:
                  opendatahub.io/connection-type: s3
                  openshift.io/display-name: multi-model-serving-ds-connection
                labels:
                  opendatahub.io/dashboard: "true"
                  opendatahub.io/managed: "true"
                name: multi-model-serving-ds-connection
              data:
                AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
                AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
              stringData:
                AWS_DEFAULT_REGION: us-east-1
                AWS_S3_BUCKET: $(BUCKETNAME)
                AWS_S3_ENDPOINT: ${MINIO_HOST}
              type: Opaque
              EOF
          command:
            - /bin/bash
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup
