apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-single-model-serving

resources:
  - ../../../../components/apps/create-bucket-job/overlays/default
  - ../../../../components/apps/upload-model-job/overlays/default
  - inference-service-granite.yaml
  - vllm-data-connection.yaml
  - serving-runtime-vllm.yaml

patches:
  - path: patch-model-details.yaml
    target:
      kind: Job
      name: upload-model-to-s3

replacements:
  - source:
      kind: Secret
      name: aws-connection-vllm
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: create-buckets
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
      - select:
          kind: Job
          name: upload-model-to-s3
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
