apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-single-model-serving

resources:
  - ../../../../components/apps/create-bucket-job/overlays/default
  - vllm-data-connection.yaml

replacements:
  - source:
      kind: Secret
      name: aws-connection-vllm
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: create-minio-buckets
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
