- op: replace
  path: /spec/source/repoURL
  value: 'https://github.com/jland-redhat/ai-accelerator.git' # Update me on fork
- op: replace
  path: /spec/source/targetRevision
  value: composer-updates
